### Get all posts
GET http://localhost:4000/feed/posts


### Create a post
POST http://localhost:4000/feed/posts
Content-Type: application/json

{
  "title": "An awesome Post",
  "content": "An awesome post content"
}